### PR TITLE
Fix bug with litre units.

### LINKED ISSUE #1313: Units ERRORS when using units derived from litre
I have a cellml model with variable units based on litre. I have defined new units derived from litre, such as 'L_per_s', 'L_per_kPa', 'L_per_s_per_kPa', etc.
However, when I generate the cellml model using Circulatory Autogen, the libcellml units check rises heaps of warnings related to units, like the one attached to this message.
The model reproducing this issue is the one in the zipped folder 'BG_cvs_MVP_model_unitsERRORS.zip'.
The only way I was able to find to fix all these units issues and to pass the libcellml units check was by using the conversion '1 litre = 1 dm^3'. In other words, in all units derived from litre, I am using 'unit meter {pref: deci, expo: 3};' instead of 'unit litre;'. The model passing the units check is the one in the zipped folder 'BG_cvs_MVP_model_unitsOK.zip'.
Please note that my model outputs were also wrong in the model with the units errors.
Could you please help me in fixing this issue?
Thanks a lot, Beatrice

Image

[BG_cvs_MVP_model_unitsERRORS.zip](https://github.com/user-attachments/files/20788798/BG_cvs_MVP_model_unitsERRORS.zip)

[BG_cvs_MVP_model_unitsOK.zip](https://github.com/user-attachments/files/20788800/BG_cvs_MVP_model_unitsOK.zip)

### PR DESCRIPTION
**Pull request by hsorby**
Fixes #1313.

### CODE REVIEW

File: src/units.cpp [hunk 1]
```diff
@@ -254,7 +254,7 @@ bool updateUnitMultiplier(const UnitsPtr &units, int direction, double &multipli
             if (isStandardUnitName(ref)) {
                 standardMult = standardMultiplierList.at(ref);
                 // Combine the information into a single local multiplier: exponent only applies to standard multiplier.
```
Comment (agarny) [inline src/units.cpp]: That comment needs updating?

File: src/units.cpp [hunk 2]
```diff
@@ -254,7 +254,7 @@ bool updateUnitMultiplier(const UnitsPtr &units, int direction, double &multipli
...
-                localMultiplier += mult + standardMult * exp + prefixMult;
+                localMultiplier += mult + standardMult * exp + prefixMult * exp;
```
Comment (agarny) [inline src/units.cpp]: Slight improvement:
```c++
localMultiplier += mult + (standardMult + prefixMult) * exp;
```

**Review by agarny — CHANGES_REQUESTED** [review]
Looks good. Just a couple of minor suggestions.

**Review by agarny — APPROVED** [review]

**Review by nickerso — APPROVED** [review]
