### PR TITLE
I629 Fixed parser bug for reading mapping ids

### LINKED ISSUE #629: Bug or feature? Mapping id the same within a connected set?
Is this a bug, or is it expected?  Two individual mappings in one component connect to the same variable in another, and they then share the same mapping id?
v1 -> v2a  } These two are the same?
v1 -> v2b  }
v1 -> v3 ... but this one is different
Any thoughts @hsorby @agarny @nickerso ?

```
TEST(Connection, mappingId)
{
    const std::string in = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                           "<model xmlns=\"http://www.cellml.org/cellml/2.0#\"  name=\"everything\" >\n"
                           "  <component name=\"c1\" >\n"
                           "    <variable name=\"v1\" units=\"units2\" interface=\"private\"/>\n"
                           "  </component>\n"
                           "  <component name=\"c2\">\n"
                           "    <variable name=\"v2a\" units=\"units2\" interface=\"public\"/>\n"
                           "    <variable name=\"v2b\" units=\"units2\" interface=\"public\"/>\n"
                           "  </component>\n"
                           "  <component name=\"c3\">\n"
                           "    <variable name=\"v3\" units=\"units2\" interface=\"public\"/>\n"
                           "  </component>\n"
                           "  <connection component_1=\"c1\" component_2=\"c2\">\n"
                           "    <map_variables variable_1=\"v1\" variable_2=\"v2a\" id=\"id12a\"/>\n"
                           "    <map_variables variable_1=\"v1\" variable_2=\"v2b\" id=\"id12b\"/>\n"
                           "  </connection>\n"
                           "  <connection component_1=\"c1\" component_2=\"c3\">\n"
                           "    <map_variables variable_1=\"v1\" variable_2=\"v3\" id=\"id13\"/>\n"
                           "  </connection>\n"

                           "</model>\n";
    auto parser = libcellml::Parser::create();
    auto model = parser->parseModel(in);
    EXPECT_EQ("id12a",
              libcellml::Variable::equivalenceMappingId(
                  model->component("c1")->variable("v1"),
                  model->component("c2")->variable("v2a")));  // <<< Fails because id is "id12b"
    EXPECT_EQ("id12b",
              libcellml::Variable::equivalenceMappingId(
                  model->component("c1")->variable("v1"),
                  model->component("c2")->variable("v2b"))); 
    EXPECT_EQ("id13",
              libcellml::Variable::equivalenceMappingId(
                  model->component("c1")->variable("v1"),
                  model->component("c3")->variable("v3")));
}
```

### PR DESCRIPTION
**Pull request by kerimoyle**
Closes #629 

The `Parser` was not saving the id of parsed mappings, but rather using the last encountered `mappingId` for all mappings in a connection.  This is fixed here.

### CODE REVIEW

File: src/parser.cpp [hunk 1]
```diff
@@ -824,6 +824,7 @@ void Parser::ParserImpl::loadConnection(const ModelPtr &model, const XmlNodePtr
             std::string variable1Name;
             std::string variable2Name;
             XmlAttributePtr childAttribute = childNode->firstAttribute();
+            mappingId = "";
```
Comment (agarny) [inline src/parser.cpp]: Might want to replace with `mappingId.clear()`.

File: src/parser.cpp [hunk 2]
```diff
@@ -891,24 +892,24 @@ void Parser::ParserImpl::loadConnection(const ModelPtr &model, const XmlNodePtr
     ComponentPtr component1 = nullptr;
     ComponentPtr component2 = nullptr;
     // Now check the objects exist in the model. TODO Remove as is validation?
-    if (model->containsComponent(componentNamePair.first)) {
-        component1 = model->component(componentNamePair.first);
+    if (model->containsComponent(componentNamePair.at(0))) {
```
Comment (agarny) [inline src/parser.cpp]: I would replace `.at(0)` with `[0]`. (Same elsewhere.)

Indeed, `.at()` is only really needed if you provide an index value that may be out of rance (in which it will raise an exception). Here, you know that the index value is fine, so no need for the "extra work" that `.at()` does.

**Review by agarny — CHANGES_REQUESTED** [review]
Looks good pending some minor changes.

File: src/parser.cpp (hunk 2 above)
Comment (kerimoyle) [reply src/parser.cpp]: 052f1676

File: src/parser.cpp (hunk 1 above)
Comment (kerimoyle) [reply src/parser.cpp]: 052f1676

File: src/parser.cpp [hunk 3]
```diff
@@ -376,7 +376,7 @@ void Parser::ParserImpl::loadModel(const ModelPtr &model, const std::string &inp
     }
 
     if (!encapsulationNodes.empty()) {
-        loadEncapsulation(model, encapsulationNodes[0]);
+        loadEncapsulation(model, encapsulationNodes.at(0));
```
Comment (agarny) [inline src/parser.cpp]: Why?

Comment (kerimoyle) [reply src/parser.cpp]: Not related to this PR, was accidental when searching for `.at`

Comment (agarny) [reply src/parser.cpp]: Ok, fair enough, although it didn't harm changing it (since the call to `.at()` doesn't account for a potential exception). Ok, added this to issue #402.

Comment (kerimoyle) [reply src/parser.cpp]: I know ... but I want this to go through as fast as poss, so I figured it was not the time to address every little thing I found along the way! Glad we have an issue for general stuff, I'll add some things there too.

**Review by agarny — DISMISSED** [review]

File: src/parser.cpp [hunk 4]
```diff
@@ -724,12 +724,12 @@ void Parser::ParserImpl::loadVariable(const VariablePtr &variable, const XmlNode
 void Parser::ParserImpl::loadConnection(const ModelPtr &model, const XmlNodePtr &node) const
 {
     // Define types for variable and component pairs.
-    using NamePair = std::pair<std::string, std::string>;
+    using NamePair = std::vector<std::string>;
```
Comment (hsorby) [inline src/parser.cpp]: This typedef doesn't make sense or give the correct information to what it is typedefing.

**Review by hsorby — CHANGES_REQUESTED** [review]
I don't understand why the component pair was changed from being a pair. It makes good sense that they are a pair because that is what they are not a vector.

File: src/parser.cpp (hunk 4 above)
Comment (kerimoyle) [reply src/parser.cpp]: > I don't understand why the component pair was changed from being a pair. It makes good sense that they are a pair because that is what they are not a vector.

It was to reuse the same typedef for the mapping. I can split it up and have four kinds if you'd rather?  Otherwise I need a type for the connection information (with 2 items) and a separate one for the mapping information (with 3 items), and then two separate collections for each of them ... it seemed better this way?

Comment (agarny) [reply src/parser.cpp]: Agreed about the naming (I completely missed that). If anything, it should be called `NameInfo`.

Comment (kerimoyle) [reply src/parser.cpp]: Compromised in 27563871

**Comment by kerimoyle** [comment]
> I don't understand why the component pair was changed from being a pair. It makes good sense that they are a pair because that is what they are not a vector.

@hsorby It was to reuse the same typedef for the mapping. I need a type for the connection information (with 2 items) and a separate one for the mapping information (with 3 items), and then two separate collections for each of them ... it just seemed better this way.  I've changed the names in the latest commit so it's clearer, but can split them up into 4 types if you'd rather.

**Comment by kerimoyle** [comment]
Reverted to three types in 75b52c70.  Re-re-re-review please @hsorby @agarny ...

**Review by hsorby — APPROVED** [review]
That looks much better to me.

**Review by agarny — APPROVED** [review]
