### PR TITLE
Fix segfault with imports across multiple directories

### LINKED ISSUE #1302: SegFault during model flattening
To try to flatten `experiments/periodic-stimulus.xml` in [Archive.zip](https://github.com/user-attachments/files/17824336/Archive.zip) results in a SegFault:
```cpp
TEST(Experiment, experiment)
{
    auto parser = libcellml::Parser::create(false);
    auto model = parser->parseModel(fileContents("importer/experiment/experiments/periodic-stimulus.xml"));

    EXPECT_EQ(size_t(0), parser->errorCount());

    auto validator = libcellml::Validator::create();

    validator->validateModel(model);

    EXPECT_EQ(size_t(0), validator->issueCount());
    EXPECT_TRUE(model->hasUnresolvedImports());

    auto importer = libcellml::Importer::create(false);

    importer->resolveImports(model, resourcePath("importer/experiment/experiments"));

    EXPECT_FALSE(model->hasUnresolvedImports());

    auto flattenModel = importer->flattenModel(model);

    EXPECT_NE(nullptr, flattenModel);
}
```

### PR DESCRIPTION
**Pull request by hsorby**
It appears the importer is not matching units correctly when importing units across multiple directories.

Fixes #1302.

### CODE REVIEW

File: tests/test_utils.cpp [hunk 1]
```diff
@@ -91,7 +91,7 @@ static const std::string FIXED_INDENT = "    ";
 
 void printComponent(const libcellml::ComponentPtr &component, size_t c, const std::string &indent, bool includeMaths)
 {
-    if (c == -1) {
+    if (c == size_t(-1)) {
```
Comment (agarny) [inline tests/test_utils.cpp]: I would replace `size_t(-1)` with `std::numeric_limits<size_t>::max()` or maybe even `SIZE_MAX` if we are ok using a `#define`.

**Review by agarny — CHANGES_REQUESTED** [review]
Looks fine pending one minor change.

File: tests/test_utils.cpp (hunk 1 above)
Comment (hsorby) [reply tests/test_utils.cpp]: [bd0b2e9](https://github.com/cellml/libcellml/pull/1304/commits/bd0b2e98adea5483741a0bad26cf7ece07c685cd)

**Review by agarny — APPROVED** [review]

**Review by nickerso — APPROVED** [review]
